import { useEffect, useState } from 'react';
import { useTerminalStore } from '../stores/terminal.js';
import { useWorkspaceStore } from '../stores/workspaces.js';

export function TerminalPage() {
  const workspaceId = useWorkspaceStore((state) => state.currentWorkspaceId);
  const { sessions, activeId, output, load, create, connect, write, close, loading, error } = useTerminalStore();
  const [input, setInput] = useState('');
  useEffect(() => { if (workspaceId) void load(workspaceId); }, [workspaceId, load]);
  useEffect(() => { if (workspaceId && activeId && !output[activeId]) connect(workspaceId, activeId); }, [workspaceId, activeId, output, connect]);
  if (!workspaceId) return <div className="p-6"><div className="rounded-3xl border border-slate-200 bg-white p-10 text-center"><h2 className="text-xl font-semibold">先选择工作区</h2><p className="mt-2 text-sm text-slate-500">终端会话会运行在当前 Workspace 目录中。</p></div></div>;
  const active = activeId ? sessions.find((session) => session.id === activeId) : undefined;
  function submit(event: React.FormEvent) { event.preventDefault(); if (!activeId || !input) return; write(activeId, `${input}\n`); setInput(''); }
  return <section className="mx-auto grid min-h-full w-full max-w-7xl grid-cols-1 gap-4 p-4 sm:p-6 lg:grid-cols-[240px_minmax(0,1fr)]"><aside className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-center justify-between"><h2 className="font-semibold">终端会话</h2><button onClick={() => void create(workspaceId)} className="rounded-lg bg-indigo-600 px-2.5 py-1.5 text-xs font-semibold text-white">新建</button></div><div className="mt-4 space-y-2">{sessions.map((session) => <button key={session.id} onClick={() => connect(workspaceId, session.id)} className={`w-full rounded-xl px-3 py-2 text-left text-sm ${session.id === activeId ? 'bg-slate-950 text-white' : 'bg-slate-50 text-slate-600'}`}><span className="block truncate">{session.id.replace('term_', '').slice(0, 12)}</span><span className="mt-1 block text-[10px] opacity-60">{session.status}</span></button>)}{!sessions.length && !loading && <p className="text-xs text-slate-400">暂无会话</p>}</div></aside><div className="flex min-h-[520px] flex-col overflow-hidden rounded-2xl border border-slate-800 bg-[#10131a] shadow-xl"><div className="flex items-center justify-between border-b border-slate-800 px-4 py-3 text-xs text-slate-400"><span>{active ? `${active.id} · ${active.status}` : '请选择终端会话'}</span>{activeId && <button onClick={() => void close(workspaceId, activeId)} className="rounded-lg px-2 py-1 text-rose-300 hover:bg-rose-950/50">关闭</button>}</div>{active?.degraded && <div className="border-b border-amber-900 bg-amber-950/30 px-4 py-2 text-xs text-amber-300">降级终端：当前使用子进程流，暂不支持真实 PTY 窗口控制。</div>}<pre className="min-h-0 flex-1 overflow-auto p-4 font-mono text-xs leading-6 text-emerald-300">{activeId ? output[activeId] || '等待终端输出…' : '创建或选择一个终端会话'}</pre><form onSubmit={submit} className="flex border-t border-slate-800 p-3"><span className="px-2 py-2 font-mono text-sm text-emerald-500">$</span><input value={input} onChange={(event) => setInput(event.target.value)} disabled={!activeId || active?.status !== 'running'} placeholder="输入命令" className="min-w-0 flex-1 bg-transparent px-2 py-2 font-mono text-sm text-white outline-none placeholder:text-slate-600" /></form>{error && <div className="border-t border-rose-900 bg-rose-950/40 px-4 py-2 text-xs text-rose-300">{error}</div>}</div></section>;
}
