import { useEffect, useState } from 'react';
import { api, getErrorMessage } from '../api/client.js';
import type { UserPublic } from '../stores/auth.js';

export function UsersPage() {
  const [users, setUsers] = useState<UserPublic[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  async function load() { setLoading(true); try { const data = await api.get<{ users: UserPublic[] }>('/api/admin/users'); setUsers(data.users); setError(null); } catch (reason) { setError(getErrorMessage(reason, '加载用户失败')); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function toggle(user: UserPublic) { try { const next = user.status === 'active' ? 'disabled' : 'active'; const data = await api.patch<{ user: UserPublic }>(`/api/admin/users/${encodeURIComponent(user.id)}`, { status: next, disable_reason: '由管理台操作' }); setUsers((items) => items.map((item) => item.id === user.id ? data.user : item)); } catch (reason) { setError(getErrorMessage(reason, '更新用户失败')); } }
  return <section className="mx-auto w-full max-w-6xl p-4 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">用户管理</h2><p className="mt-1 text-sm text-slate-500">查看账号状态并执行启用/禁用操作。</p></div><button onClick={() => void load()} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-medium">刷新</button></div>{error && <div role="alert" className="mt-4 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}<div className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{loading ? <div className="p-8 text-center text-sm text-slate-400">正在加载…</div> : <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-400"><tr><th className="px-4 py-3">用户</th><th className="px-4 py-3">角色</th><th className="px-4 py-3">权限</th><th className="px-4 py-3">状态</th><th className="px-4 py-3" /></tr></thead><tbody>{users.map((user) => <tr key={user.id} className="border-t border-slate-100"><td className="px-4 py-3"><div className="font-medium">{user.display_name}</div><div className="mt-1 text-xs text-slate-400">@{user.username}</div></td><td className="px-4 py-3 text-slate-500">{user.role === 'admin' ? '管理员' : '成员'}</td><td className="max-w-[260px] truncate px-4 py-3 text-xs text-slate-400">{user.permissions?.join('、') || '基础权限'}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-xs ${user.status === 'active' ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{user.status === 'active' ? '正常' : user.status === 'disabled' ? '已禁用' : '已删除'}</span></td><td className="px-4 py-3 text-right">{user.status !== 'deleted' && <button onClick={() => void toggle(user)} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs hover:bg-slate-50">{user.status === 'active' ? '禁用' : '启用'}</button>}</td></tr>)}</tbody></table></div>}</div></section>;
}
